// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piayqbzlvwcfjomesnoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYXlxYnpsdndjZmpvbWVzbm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjQ3NTMsImV4cCI6MjA2NjYwMDc1M30.Up50_P_GVkwbHKuTgIswTC1oK1-iOPQt7XNSLKCmyVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);